name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: installation
      run: npm i
    - name: test
      run: npm run test
    - name: build
      run: npm run build
